// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all labels
	// (GET /labels)
	GetLabels(c *gin.Context)
	// Get all rules
	// (GET /rules)
	GetRules(c *gin.Context)
	// Create rule
	// (POST /rules)
	CreateRule(c *gin.Context)
	// Apply all rules
	// (POST /rules/process)
	ProcessRules(c *gin.Context)
	// Delete rule
	// (DELETE /rules/{id})
	DeleteRule(c *gin.Context, id string)
	// Update rule
	// (PUT /rules/{id})
	UpdateRule(c *gin.Context, id string)
	// Apply specific rule
	// (POST /rules/{id}/process)
	ProcessRule(c *gin.Context, id string)
	// Get transactions
	// (GET /transactions)
	GetTransactions(c *gin.Context, params GetTransactionsParams)
	// Create transaction
	// (POST /transactions)
	CreateTransaction(c *gin.Context)
	// Import transactions
	// (POST /transactions/import)
	ImportTransactions(c *gin.Context)
	// Delete transaction
	// (DELETE /transactions/{id})
	DeleteTransaction(c *gin.Context, id int64)
	// Get transaction by id
	// (GET /transactions/{id})
	GetTransaction(c *gin.Context, id int64)
	// Update transaction info
	// (PATCH /transactions/{id})
	PatchTransactionInfo(c *gin.Context, id int64)
	// Update transaction
	// (PUT /transactions/{id})
	UpdateTransaction(c *gin.Context, id int64)
	// Remove all labels from transaction
	// (DELETE /transactions/{id}/labels)
	RemoveTransactionLabels(c *gin.Context, id int64)
	// Get transaction labels
	// (GET /transactions/{id}/labels)
	GetTransactionLabels(c *gin.Context, id int64)
	// Add label to transaction
	// (POST /transactions/{id}/labels)
	AddTransactionLabel(c *gin.Context, id int64)
	// Remove specific label from transaction
	// (DELETE /transactions/{id}/labels/{labelId})
	RemoveTransactionLabel(c *gin.Context, id int64, labelId int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetLabels operation middleware
func (siw *ServerInterfaceWrapper) GetLabels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLabels(c)
}

// GetRules operation middleware
func (siw *ServerInterfaceWrapper) GetRules(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRules(c)
}

// CreateRule operation middleware
func (siw *ServerInterfaceWrapper) CreateRule(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRule(c)
}

// ProcessRules operation middleware
func (siw *ServerInterfaceWrapper) ProcessRules(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProcessRules(c)
}

// DeleteRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRule(c, id)
}

// UpdateRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateRule(c, id)
}

// ProcessRule operation middleware
func (siw *ServerInterfaceWrapper) ProcessRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProcessRule(c, id)
}

// GetTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetTransactions(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionsParams

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "startDate", c.Request.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter startDate: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "endDate", c.Request.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter endDate: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransactions(c, params)
}

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTransaction(c)
}

// ImportTransactions operation middleware
func (siw *ServerInterfaceWrapper) ImportTransactions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ImportTransactions(c)
}

// DeleteTransaction operation middleware
func (siw *ServerInterfaceWrapper) DeleteTransaction(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTransaction(c, id)
}

// GetTransaction operation middleware
func (siw *ServerInterfaceWrapper) GetTransaction(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransaction(c, id)
}

// PatchTransactionInfo operation middleware
func (siw *ServerInterfaceWrapper) PatchTransactionInfo(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchTransactionInfo(c, id)
}

// UpdateTransaction operation middleware
func (siw *ServerInterfaceWrapper) UpdateTransaction(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTransaction(c, id)
}

// RemoveTransactionLabels operation middleware
func (siw *ServerInterfaceWrapper) RemoveTransactionLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveTransactionLabels(c, id)
}

// GetTransactionLabels operation middleware
func (siw *ServerInterfaceWrapper) GetTransactionLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransactionLabels(c, id)
}

// AddTransactionLabel operation middleware
func (siw *ServerInterfaceWrapper) AddTransactionLabel(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddTransactionLabel(c, id)
}

// RemoveTransactionLabel operation middleware
func (siw *ServerInterfaceWrapper) RemoveTransactionLabel(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "labelId" -------------
	var labelId int

	err = runtime.BindStyledParameterWithOptions("simple", "labelId", c.Param("labelId"), &labelId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter labelId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveTransactionLabel(c, id, labelId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/labels", wrapper.GetLabels)
	router.GET(options.BaseURL+"/rules", wrapper.GetRules)
	router.POST(options.BaseURL+"/rules", wrapper.CreateRule)
	router.POST(options.BaseURL+"/rules/process", wrapper.ProcessRules)
	router.DELETE(options.BaseURL+"/rules/:id", wrapper.DeleteRule)
	router.PUT(options.BaseURL+"/rules/:id", wrapper.UpdateRule)
	router.POST(options.BaseURL+"/rules/:id/process", wrapper.ProcessRule)
	router.GET(options.BaseURL+"/transactions", wrapper.GetTransactions)
	router.POST(options.BaseURL+"/transactions", wrapper.CreateTransaction)
	router.POST(options.BaseURL+"/transactions/import", wrapper.ImportTransactions)
	router.DELETE(options.BaseURL+"/transactions/:id", wrapper.DeleteTransaction)
	router.GET(options.BaseURL+"/transactions/:id", wrapper.GetTransaction)
	router.PATCH(options.BaseURL+"/transactions/:id", wrapper.PatchTransactionInfo)
	router.PUT(options.BaseURL+"/transactions/:id", wrapper.UpdateTransaction)
	router.DELETE(options.BaseURL+"/transactions/:id/labels", wrapper.RemoveTransactionLabels)
	router.GET(options.BaseURL+"/transactions/:id/labels", wrapper.GetTransactionLabels)
	router.POST(options.BaseURL+"/transactions/:id/labels", wrapper.AddTransactionLabel)
	router.DELETE(options.BaseURL+"/transactions/:id/labels/:labelId", wrapper.RemoveTransactionLabel)
}
