// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"time"
)

// Defines values for TransactionKind.
const (
	Credit TransactionKind = "credit"
	Debit  TransactionKind = "debit"
)

// CreateRuleRequest defines model for CreateRuleRequest.
type CreateRuleRequest struct {
	Filter string   `json:"filter"`
	Name   string   `json:"name"`
	Tags   []string `json:"tags"`
}

// CreateTransactionRequest defines model for CreateTransactionRequest.
type CreateTransactionRequest struct {
	Account   int64           `json:"account"`
	Amount    float64         `json:"amount"`
	Content   string          `json:"content"`
	Date      time.Time       `json:"date"`
	Info      *string         `json:"info,omitempty"`
	Kind      TransactionKind `json:"kind"`
	Recipient *string         `json:"recipient,omitempty"`
}

// Rule defines model for Rule.
type Rule struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Filter    string     `json:"filter"`
	Id        int        `json:"id"`
	Name      string     `json:"name"`
	Tags      []string   `json:"tags"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Account   int64           `json:"account"`
	Amount    float64         `json:"amount"`
	Content   string          `json:"content"`
	Date      time.Time       `json:"date"`
	Hash      string          `json:"hash"`
	Id        int64           `json:"id"`
	Info      *string         `json:"info,omitempty"`
	Kind      TransactionKind `json:"kind"`
	Recipient *string         `json:"recipient,omitempty"`
	Tags      []string        `json:"tags"`
}

// TransactionKind defines model for TransactionKind.
type TransactionKind string

// UpdateRuleRequest defines model for UpdateRuleRequest.
type UpdateRuleRequest struct {
	Filter string   `json:"filter"`
	Name   string   `json:"name"`
	Tags   []string `json:"tags"`
}

// UpdateTransactionRequest defines model for UpdateTransactionRequest.
type UpdateTransactionRequest struct {
	Account   int64           `json:"account"`
	Amount    float64         `json:"amount"`
	Content   string          `json:"content"`
	Date      time.Time       `json:"date"`
	Info      *string         `json:"info,omitempty"`
	Kind      TransactionKind `json:"kind"`
	Recipient *string         `json:"recipient,omitempty"`
}

// ListRulesParams defines parameters for ListRules.
type ListRulesParams struct {
	// Filter Filter DSL expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// Filter Filter DSL expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = CreateRuleRequest

// UpdateRuleJSONRequestBody defines body for UpdateRule for application/json ContentType.
type UpdateRuleJSONRequestBody = UpdateRuleRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// UpdateTransactionJSONRequestBody defines body for UpdateTransaction for application/json ContentType.
type UpdateTransactionJSONRequestBody = UpdateTransactionRequest
