// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TransactionKind.
const (
	Credit TransactionKind = "credit"
	Debit  TransactionKind = "debit"
)

// BalanceTrendPoint defines model for BalanceTrendPoint.
type BalanceTrendPoint struct {
	Balance float64 `json:"balance"`
	Credit  float64 `json:"credit"`
	Debit   float64 `json:"debit"`
	Month   string  `json:"month"`
}

// CreateRuleRequest defines model for CreateRuleRequest.
type CreateRuleRequest struct {
	Filter string   `json:"filter"`
	Name   string   `json:"name"`
	Tags   []string `json:"tags"`
}

// CreateTransactionRequest defines model for CreateTransactionRequest.
type CreateTransactionRequest struct {
	Account   int64           `json:"account"`
	Amount    float64         `json:"amount"`
	Content   string          `json:"content"`
	Date      time.Time       `json:"date"`
	Info      *string         `json:"info,omitempty"`
	Kind      TransactionKind `json:"kind"`
	Recipient *string         `json:"recipient,omitempty"`
}

// ImportFileResult defines model for ImportFileResult.
type ImportFileResult struct {
	Created  int    `json:"created"`
	Errors   int    `json:"errors"`
	Filename string `json:"filename"`
	Skipped  int    `json:"skipped"`
}

// ImportResponse defines model for ImportResponse.
type ImportResponse struct {
	Files   []ImportFileResult `json:"files"`
	Message string             `json:"message"`
}

// Rule defines model for Rule.
type Rule struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Filter    string     `json:"filter"`
	Id        int        `json:"id"`
	Name      string     `json:"name"`
	Tags      []string   `json:"tags"`
}

// SummaryOverview defines model for SummaryOverview.
type SummaryOverview struct {
	Balance           float64 `json:"balance"`
	TotalCredit       float64 `json:"total_credit"`
	TotalDebit        float64 `json:"total_debit"`
	TotalTransactions int     `json:"total_transactions"`
	UniqueAccounts    int     `json:"unique_accounts"`
	UniqueTags        int     `json:"unique_tags"`
}

// TagSummary defines model for TagSummary.
type TagSummary struct {
	Count       int     `json:"count"`
	Tag         string  `json:"tag"`
	TotalCredit float64 `json:"total_credit"`
	TotalDebit  float64 `json:"total_debit"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Account   int64           `json:"account"`
	Amount    float64         `json:"amount"`
	Content   string          `json:"content"`
	Date      time.Time       `json:"date"`
	Hash      string          `json:"hash"`
	Id        int64           `json:"id"`
	Info      *string         `json:"info,omitempty"`
	Kind      TransactionKind `json:"kind"`
	Recipient *string         `json:"recipient,omitempty"`
	Tags      []string        `json:"tags"`
}

// TransactionKind defines model for TransactionKind.
type TransactionKind string

// TransactionList defines model for TransactionList.
type TransactionList struct {
	Items []Transaction `json:"items"`

	// Total Total number of matching transactions (before pagination)
	Total int `json:"total"`
}

// UpdateRuleRequest defines model for UpdateRuleRequest.
type UpdateRuleRequest struct {
	Filter string   `json:"filter"`
	Name   string   `json:"name"`
	Tags   []string `json:"tags"`
}

// UpdateTransactionRequest defines model for UpdateTransactionRequest.
type UpdateTransactionRequest struct {
	Info *string `json:"info,omitempty"`
}

// ListRulesParams defines parameters for ListRules.
type ListRulesParams struct {
	// Filter Filter DSL expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSummaryBalanceTrendParams defines parameters for GetSummaryBalanceTrend.
type GetSummaryBalanceTrendParams struct {
	// Filter Filter DSL expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetSummaryByTagParams defines parameters for GetSummaryByTag.
type GetSummaryByTagParams struct {
	// Filter Filter DSL expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetSummaryOverviewParams defines parameters for GetSummaryOverview.
type GetSummaryOverviewParams struct {
	// Filter Filter DSL expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// Filter Filter DSL expression
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Sort fields with direction (e.g., "date:desc" or "amount:asc"). Valid fields: date, amount, kind, account.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`
}

// ImportTransactionsMultipartBody defines parameters for ImportTransactions.
type ImportTransactionsMultipartBody struct {
	// Account Account number to assign to CSV imports
	Account *int64               `json:"account,omitempty"`
	Files   []openapi_types.File `json:"files"`
}

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = CreateRuleRequest

// UpdateRuleJSONRequestBody defines body for UpdateRule for application/json ContentType.
type UpdateRuleJSONRequestBody = UpdateRuleRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// ImportTransactionsMultipartRequestBody defines body for ImportTransactions for multipart/form-data ContentType.
type ImportTransactionsMultipartRequestBody ImportTransactionsMultipartBody

// UpdateTransactionJSONRequestBody defines body for UpdateTransaction for application/json ContentType.
type UpdateTransactionJSONRequestBody = UpdateTransactionRequest
