// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package pg

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type RuleFilterOption func(r *RuleFilter)

// NewRuleFilterWithOptions creates a new RuleFilter with the passed in options set
func NewRuleFilterWithOptions(opts ...RuleFilterOption) *RuleFilter {
	r := &RuleFilter{}
	for _, o := range opts {
		o(r)
	}
	return r
}

// NewRuleFilterWithOptionsAndDefaults creates a new RuleFilter with the passed in options set starting from the defaults
func NewRuleFilterWithOptionsAndDefaults(opts ...RuleFilterOption) *RuleFilter {
	r := &RuleFilter{}
	defaults.MustSet(r)
	for _, o := range opts {
		o(r)
	}
	return r
}

// ToOption returns a new RuleFilterOption that sets the values from the passed in RuleFilter
func (r *RuleFilter) ToOption() RuleFilterOption {
	return func(to *RuleFilter) {
		to.Name = r.Name
	}
}

// DebugMap returns a map form of RuleFilter for debugging
func (r RuleFilter) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Name"] = helpers.DebugValue(r.Name, false)
	return debugMap
}

// RuleFilterWithOptions configures an existing RuleFilter with the passed in options set
func RuleFilterWithOptions(r *RuleFilter, opts ...RuleFilterOption) *RuleFilter {
	for _, o := range opts {
		o(r)
	}
	return r
}

// WithOptions configures the receiver RuleFilter with the passed in options set
func (r *RuleFilter) WithOptions(opts ...RuleFilterOption) *RuleFilter {
	for _, o := range opts {
		o(r)
	}
	return r
}

// WithName returns an option that can set Name on a RuleFilter
func WithName(name *string) RuleFilterOption {
	return func(r *RuleFilter) {
		r.Name = name
	}
}
