// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package pg

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
	"time"
)

type TransactionFilterOption func(t *TransactionFilter)

// NewTransactionFilterWithOptions creates a new TransactionFilter with the passed in options set
func NewTransactionFilterWithOptions(opts ...TransactionFilterOption) *TransactionFilter {
	t := &TransactionFilter{}
	for _, o := range opts {
		o(t)
	}
	return t
}

// NewTransactionFilterWithOptionsAndDefaults creates a new TransactionFilter with the passed in options set starting from the defaults
func NewTransactionFilterWithOptionsAndDefaults(opts ...TransactionFilterOption) *TransactionFilter {
	t := &TransactionFilter{}
	defaults.MustSet(t)
	for _, o := range opts {
		o(t)
	}
	return t
}

// ToOption returns a new TransactionFilterOption that sets the values from the passed in TransactionFilter
func (t *TransactionFilter) ToOption() TransactionFilterOption {
	return func(to *TransactionFilter) {
		to.After = t.After
		to.Before = t.Before
	}
}

// DebugMap returns a map form of TransactionFilter for debugging
func (t TransactionFilter) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["After"] = helpers.DebugValue(t.After, false)
	debugMap["Before"] = helpers.DebugValue(t.Before, false)
	return debugMap
}

// TransactionFilterWithOptions configures an existing TransactionFilter with the passed in options set
func TransactionFilterWithOptions(t *TransactionFilter, opts ...TransactionFilterOption) *TransactionFilter {
	for _, o := range opts {
		o(t)
	}
	return t
}

// WithOptions configures the receiver TransactionFilter with the passed in options set
func (t *TransactionFilter) WithOptions(opts ...TransactionFilterOption) *TransactionFilter {
	for _, o := range opts {
		o(t)
	}
	return t
}

// WithAfter returns an option that can set After on a TransactionFilter
func WithAfter(after *time.Time) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.After = after
	}
}

// WithBefore returns an option that can set Before on a TransactionFilter
func WithBefore(before *time.Time) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.Before = before
	}
}
