// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package pg

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type QueryTransactionOptionsOption func(q *QueryTransactionOptions)

// NewQueryTransactionOptionsWithOptions creates a new QueryTransactionOptions with the passed in options set
func NewQueryTransactionOptionsWithOptions(opts ...QueryTransactionOptionsOption) *QueryTransactionOptions {
	q := &QueryTransactionOptions{}
	for _, o := range opts {
		o(q)
	}
	return q
}

// NewQueryTransactionOptionsWithOptionsAndDefaults creates a new QueryTransactionOptions with the passed in options set starting from the defaults
func NewQueryTransactionOptionsWithOptionsAndDefaults(opts ...QueryTransactionOptionsOption) *QueryTransactionOptions {
	q := &QueryTransactionOptions{}
	defaults.MustSet(q)
	for _, o := range opts {
		o(q)
	}
	return q
}

// ToOption returns a new QueryTransactionOptionsOption that sets the values from the passed in QueryTransactionOptions
func (q *QueryTransactionOptions) ToOption() QueryTransactionOptionsOption {
	return func(to *QueryTransactionOptions) {
		to.Limit = q.Limit
		to.Offset = q.Offset
	}
}

// DebugMap returns a map form of QueryTransactionOptions for debugging
func (q QueryTransactionOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Limit"] = helpers.DebugValue(q.Limit, false)
	debugMap["Offset"] = helpers.DebugValue(q.Offset, false)
	return debugMap
}

// QueryTransactionOptionsWithOptions configures an existing QueryTransactionOptions with the passed in options set
func QueryTransactionOptionsWithOptions(q *QueryTransactionOptions, opts ...QueryTransactionOptionsOption) *QueryTransactionOptions {
	for _, o := range opts {
		o(q)
	}
	return q
}

// WithOptions configures the receiver QueryTransactionOptions with the passed in options set
func (q *QueryTransactionOptions) WithOptions(opts ...QueryTransactionOptionsOption) *QueryTransactionOptions {
	for _, o := range opts {
		o(q)
	}
	return q
}

// WithLimit returns an option that can set Limit on a QueryTransactionOptions
func WithLimit(limit int) QueryTransactionOptionsOption {
	return func(q *QueryTransactionOptions) {
		q.Limit = limit
	}
}

// WithOffset returns an option that can set Offset on a QueryTransactionOptions
func WithOffset(offset int) QueryTransactionOptionsOption {
	return func(q *QueryTransactionOptions) {
		q.Offset = offset
	}
}
