// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package server

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
	"time"
)

type RunnableServerConfigOption func(r *RunnableServerConfig)

// NewRunnableServerConfigWithOptions creates a new RunnableServerConfig with the passed in options set
func NewRunnableServerConfigWithOptions(opts ...RunnableServerConfigOption) *RunnableServerConfig {
	r := &RunnableServerConfig{}
	for _, o := range opts {
		o(r)
	}
	return r
}

// NewRunnableServerConfigWithOptionsAndDefaults creates a new RunnableServerConfig with the passed in options set starting from the defaults
func NewRunnableServerConfigWithOptionsAndDefaults(opts ...RunnableServerConfigOption) *RunnableServerConfig {
	r := &RunnableServerConfig{}
	defaults.MustSet(r)
	for _, o := range opts {
		o(r)
	}
	return r
}

// ToOption returns a new RunnableServerConfigOption that sets the values from the passed in RunnableServerConfig
func (r *RunnableServerConfig) ToOption() RunnableServerConfigOption {
	return func(to *RunnableServerConfig) {
		to.PostgresURI = r.PostgresURI
		to.GraceTimeout = r.GraceTimeout
		to.Port = r.Port
	}
}

// DebugMap returns a map form of RunnableServerConfig for debugging
func (r RunnableServerConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["PostgresURI"] = helpers.DebugValue(r.PostgresURI, false)
	debugMap["GraceTimeout"] = helpers.DebugValue(r.GraceTimeout, false)
	debugMap["Port"] = helpers.DebugValue(r.Port, false)
	return debugMap
}

// RunnableServerConfigWithOptions configures an existing RunnableServerConfig with the passed in options set
func RunnableServerConfigWithOptions(r *RunnableServerConfig, opts ...RunnableServerConfigOption) *RunnableServerConfig {
	for _, o := range opts {
		o(r)
	}
	return r
}

// WithOptions configures the receiver RunnableServerConfig with the passed in options set
func (r *RunnableServerConfig) WithOptions(opts ...RunnableServerConfigOption) *RunnableServerConfig {
	for _, o := range opts {
		o(r)
	}
	return r
}

// WithPostgresURI returns an option that can set PostgresURI on a RunnableServerConfig
func WithPostgresURI(postgresURI string) RunnableServerConfigOption {
	return func(r *RunnableServerConfig) {
		r.PostgresURI = postgresURI
	}
}

// WithGraceTimeout returns an option that can set GraceTimeout on a RunnableServerConfig
func WithGraceTimeout(graceTimeout time.Duration) RunnableServerConfigOption {
	return func(r *RunnableServerConfig) {
		r.GraceTimeout = graceTimeout
	}
}

// WithPort returns an option that can set Port on a RunnableServerConfig
func WithPort(port int) RunnableServerConfigOption {
	return func(r *RunnableServerConfig) {
		r.Port = port
	}
}
