// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package services

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
	"time"
)

type TransactionFilterOption func(t *TransactionFilter)

// NewTransactionFilterWithOptions creates a new TransactionFilter with the passed in options set
func NewTransactionFilterWithOptions(opts ...TransactionFilterOption) *TransactionFilter {
	t := &TransactionFilter{}
	for _, o := range opts {
		o(t)
	}
	return t
}

// NewTransactionFilterWithOptionsAndDefaults creates a new TransactionFilter with the passed in options set starting from the defaults
func NewTransactionFilterWithOptionsAndDefaults(opts ...TransactionFilterOption) *TransactionFilter {
	t := &TransactionFilter{}
	defaults.MustSet(t)
	for _, o := range opts {
		o(t)
	}
	return t
}

// ToOption returns a new TransactionFilterOption that sets the values from the passed in TransactionFilter
func (t *TransactionFilter) ToOption() TransactionFilterOption {
	return func(to *TransactionFilter) {
		to.Start = t.Start
		to.End = t.End
		to.Labels = t.Labels
		to.Limit = t.Limit
		to.Offset = t.Offset
	}
}

// DebugMap returns a map form of TransactionFilter for debugging
func (t TransactionFilter) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Start"] = helpers.DebugValue(t.Start, false)
	debugMap["End"] = helpers.DebugValue(t.End, false)
	debugMap["Labels"] = helpers.DebugValue(t.Labels, false)
	debugMap["Limit"] = helpers.DebugValue(t.Limit, false)
	debugMap["Offset"] = helpers.DebugValue(t.Offset, false)
	return debugMap
}

// TransactionFilterWithOptions configures an existing TransactionFilter with the passed in options set
func TransactionFilterWithOptions(t *TransactionFilter, opts ...TransactionFilterOption) *TransactionFilter {
	for _, o := range opts {
		o(t)
	}
	return t
}

// WithOptions configures the receiver TransactionFilter with the passed in options set
func (t *TransactionFilter) WithOptions(opts ...TransactionFilterOption) *TransactionFilter {
	for _, o := range opts {
		o(t)
	}
	return t
}

// WithStart returns an option that can set Start on a TransactionFilter
func WithStart(start *time.Time) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.Start = start
	}
}

// WithEnd returns an option that can set End on a TransactionFilter
func WithEnd(end *time.Time) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.End = end
	}
}

// WithLabels returns an option that can append Labelss to TransactionFilter.Labels
func WithLabels(labels string) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.Labels = append(t.Labels, labels)
	}
}

// SetLabels returns an option that can set Labels on a TransactionFilter
func SetLabels(labels []string) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.Labels = labels
	}
}

// WithLimit returns an option that can set Limit on a TransactionFilter
func WithLimit(limit int) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.Limit = limit
	}
}

// WithOffset returns an option that can set Offset on a TransactionFilter
func WithOffset(offset int) TransactionFilterOption {
	return func(t *TransactionFilter) {
		t.Offset = offset
	}
}
