// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package config

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type DatabaseOption func(d *Database)

// NewDatabaseWithOptions creates a new Database with the passed in options set
func NewDatabaseWithOptions(opts ...DatabaseOption) *Database {
	d := &Database{}
	for _, o := range opts {
		o(d)
	}
	return d
}

// NewDatabaseWithOptionsAndDefaults creates a new Database with the passed in options set starting from the defaults
func NewDatabaseWithOptionsAndDefaults(opts ...DatabaseOption) *Database {
	d := &Database{}
	defaults.MustSet(d)
	for _, o := range opts {
		o(d)
	}
	return d
}

// ToOption returns a new DatabaseOption that sets the values from the passed in Database
func (d *Database) ToOption() DatabaseOption {
	return func(to *Database) {
		to.URI = d.URI
	}
}

// DebugMap returns a map form of Database for debugging
func (d Database) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["URI"] = helpers.DebugValue(d.URI, false)
	return debugMap
}

// DatabaseWithOptions configures an existing Database with the passed in options set
func DatabaseWithOptions(d *Database, opts ...DatabaseOption) *Database {
	for _, o := range opts {
		o(d)
	}
	return d
}

// WithOptions configures the receiver Database with the passed in options set
func (d *Database) WithOptions(opts ...DatabaseOption) *Database {
	for _, o := range opts {
		o(d)
	}
	return d
}

// WithURI returns an option that can set URI on a Database
func WithURI(uRI string) DatabaseOption {
	return func(d *Database) {
		d.URI = uRI
	}
}
